# yamllint disable rule:line-length
log_configs:
  - path: /workspaces/live-node-monitor/zuul-logs/*.log
    events:
      - name: "smrt_event"
        regexes:
          - '\[SMRT\] (?P<content>.*)'
        targets:
          - name: elasticsearch
            config:
              index: "log_monitor_smrt_retry"
      - name: "bazel_actions"
        regexes:
          - '\d+ actions executed. \d+ remote \d+ local'  # What if a bazel execution does not have "remote" actions? Can a regex group be optional?
        targets:
          - name: elasticsearch
            config:
              index: "log_monitor_bazel_actions"
      - name: "error_event"
        regexes:
          - '(?P<level>ERROR|CRITICAL): (?P<message>.+)$'
        targets:
          - name: elasticsearch
            config:
              index: "log_monitor_error_events"
      - name: "some_json_line"
        regexes:
          - 'json: (?P<json>\{.+:.+\})'
        targets:
          - name: elasticsearch
            config:
              index: "log_monitor_json_events"

cmd_configs:
  # TODO: Path and events might not be needed here, as this is not reacting to events
  # But how to generalize configs so that they are similar?
  - events:
      - name: vmstat-oom
        command: "ls -la"
        targets:
          - name: elasticsearch
            config:
              index: "cmd_monitor_vmstat"
      - name: ls la
        command: "ls -la"
        repeat: 15.0
        chdir: "/tmp"
        targets:
          - name: elasticsearch
            config:
              index: "cmd_monitor_ls"
