name: yamllint
on: push
permissions:
  contents: read
jobs:
  build:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v7
      - name: 🚀 Run yamllint
        run: |
          yamllint .
